-- zinogre_hit.lua — GENERATED by mhfu_monster_editor.runtime from ports/zinogre.toml
-- (1 volume(s), 2 grid state(s), 1 attack set(s), 2 attack record(s), id 86c5dea2). Do not edit: re-export from the
-- editor's Parts panel or `python -m mhfu_monster_editor.runtime ports/zinogre.toml`.
--
-- The port's hit tables as `mhfu_port.lua`'s P.hit() writes them into the
-- running game: the collision volumes IN PLACE over the host species' own set
-- (its game_task.ovl row's +0x240 pointer), sentinel-terminated, and the
-- damage grid over the species' 0x48 state blocks. Both land once the port's
-- entity is live in-area and are re-checked every tick (issue #19).
-- The attack side (#33): each [[hitbox]] set IN PLACE over the host's own set
-- of that index through the overlay's set-pointer table, sentinel-terminated,
-- refused if the live set's count is not `cap`; each [[attack]] writes only
-- the levers it names into the 0x18 record (+0x02 power, +0x09 element,
-- +0x0A volume).
-- Host set capacity: 42 record(s).

mhfu.port = mhfu.port or { _queue = {} }
mhfu.port.mod = mhfu.port.mod or function(n, f) mhfu.port._queue[n] = f end

mhfu.port.mod("zinogre_hit", function(P)
  P.hit("zinogre", {
    species = 75,
    id = "86c5dea2",
    -- bone, shape(0 sphere/1 capsule), hitzone_row, part, flags, radius, ax, ay, az, bx, by, bz
    volumes = {
      { 35, 0, 0, 0, 0x8000000, 230.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
    },
    -- per state: 7 rows x (raw cut impact shot fire water dragon thunder ice ko)
    grid = {
      {  -- normal
        { 100, 255, 255, 255, 0, 15, 5, 30, 20, 110 },
        { 90, 255, 255, 255, 0, 10, 5, 20, 15, 0 },
        { 80, 255, 255, 255, 15, 15, 10, 25, 15, 0 },
        { 70, 255, 255, 255, 0, 15, 10, 25, 5, 10 },
        { 60, 255, 255, 255, 0, 5, 0, 15, 15, 0 },
        { 50, 255, 255, 255, 0, 15, 10, 20, 15, 0 },
        { 40, 255, 255, 255, 0, 5, 0, 10, 5, 0 },
      },
      {  -- enraged
        { 100, 80, 70, 45, 0, 15, 5, 35, 20, 150 },
        { 90, 55, 55, 20, 0, 10, 5, 20, 15, 0 },
        { 80, 30, 35, 20, 15, 15, 10, 25, 15, 0 },
        { 70, 50, 45, 20, 0, 15, 10, 25, 5, 0 },
        { 60, 35, 30, 10, 0, 5, 0, 15, 15, 0 },
        { 50, 30, 25, 30, 0, 15, 10, 25, 15, 0 },
        { 40, 40, 45, 40, 0, 5, 0, 10, 5, 0 },
      },
    },
    -- where host em75 keeps its attack data (static, the overlay's own)
    attack_tables = { volumes = 0x09D60768, records = 0x09D60848, n_sets = 56, n_records = 107 },
    -- per set: cap = the host's record count (the in-place limit AND the fingerprint);
    -- rows: bone, shape(0 sphere/1 capsule), 0, 0, flags, radius, ax, ay, az, bx, by, bz
    attack_sets = {
      [2] = { cap = 10, volumes = {
        { 10, 0, 0, 0, 0x0, 150.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 18, 0, 0, 0, 0x0, 150.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 34, 0, 0, 0, 0x0, 250.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 4, 0, 0, 0, 0x0, 250.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 2, 0, 0, 0, 0x0, 250.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 41, 0, 0, 0, 0x0, 250.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 125, 1, 0, 0, 0x0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },  -- marker
        { 42, 0, 0, 0, 0x0, 200.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 43, 0, 0, 0, 0x0, 120.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
        { 10, 0, 0, 0, 0x0, 600.0, -550.0, -50.0, 150.0, 0.0, 0.0, 0.0 },
      } },
    },
    -- the levers on a record; nil = the host's byte stands
    attacks = {
      { id = 6, power = 8, element = nil, volume = nil },  -- the charge — testing power; the native is 64 (-72 HP)
      { id = 31, power = 4, element = nil, volume = nil },  -- the charge's second attack; native 30
    },
  })
end)
